export const BOOKMARK_NAME_MAX_LENGTH = 100
export const TAG_NAME_MAX_LENGTH = 50
export const FOLDER_NAME_MAX_LENGTH = 50
export const DESCRIPTION_MAX_LENGTH = 100
export const PASSWORD_MIN_LENGTH = 8
export const PASSWORD_MAX_LENGTH = 128
