import { GeistSans } from 'geist/font/sans'
import type { Metadata } from 'next'
import { Providers } from '@/components/providers'
import '@/styles/globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${GeistSans.variable} antialiased`}>
        <Providers>
          <main className="relative flex min-h-dvh flex-col">{children}</main>
        </Providers>
      </body>
    </html>
  )
}
